### ISSUE TITLE
multiple connection 

### ISSUE THREAD

**Issue by exist16** [Rickedb/OpenProtocolInterpreter#15]
is there any way to manage multiple open protocol connections using this dll?

**Comment by Rickedb** [comment]
Is this question about the sample project or the lib itself?

**If it is about the lib:** 
Is just a parser, it's possible to implement a multi-threaded application and use it, but it won't handle multiple by itself, you must implement your way.

**If it is about the sample:**
Since it's just a sample to people understand how it works. 
By now, I have no intentions to make it a robust WinForm application that communicates with multiple tightening controllers. Maybe later if many people request it.
